[Server] FCM PUSH 모듈
CMI-OSS/cbnu-alrami pull request #136
Opened 2022-03-27 10:11 UTC by ionc635

## 👀 이슈

resolve #126

## 📌 개요

Nest.js에 맞게 FCM PUSH 모듈을 만듭니다.

## 👩‍💻 작업 사항

fcm-node 의존성 설치
fcm module 생성
fcm interface 생성
FCM PUSH 기능 구현

## ✅ 참고 사항

serverKey는 추후 동적 모듈 적용할 계획입니다.

2022-03-27 10:25 UTC, jaryapp approved these changes
스티븐 충림이 첫 PR 환영합니다 🥳🥳

2022-03-27 10:25 UTC, jaryapp commented on packages/server/src/fcm/fcm.service.ts
> +  public send_notice(to: string, data: Data) {
함수명은 camelCase로 통일 부탁드려요~

2022-03-27 10:27 UTC, jaryapp commented on packages/server/src/fcm/fcm.service.ts
> +    this.message = (to: string, data: Data, collapse_key: string) => ({
message함수를 class의 멤버함수가 아니라 멤버변수로 정의한 이유가 있을까요?

2022-03-27 10:34 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +  public send_notice(to: string, data: Data) {
네 확인했습니다!

2022-03-27 10:34 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +    this.message = (to: string, data: Data, collapse_key: string) => ({
특별한 이유는 없습니다. 수정하는게 좋을까요?

2022-03-27 10:36 UTC, jaryapp commented on packages/server/src/fcm/fcm.service.ts
> +    this.message = (to: string, data: Data, collapse_key: string) => ({
@ionc635 
넵 함수는 멤버함수로 관리하는것이 통일성 있을것 같아요~

2022-03-27 10:53 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +    this.message = (to: string, data: Data, collapse_key: string) => ({
네 확인했습니다!

2022-03-29 01:39 UTC, JeongHyeongKim requested changes

2022-03-29 01:39 UTC, JeongHyeongKim commented on packages/server/src/fcm/fcm.service.ts
> +  }
아래 function의 경우, IOS를 위해 쓰이는것이 명확하나, comment 드린 function은 어떤 체제에서 동작하는지 명확하지 않아 아래 function naming과 통일하는 것이 좋아보입니다.

ex) sendNoticeAndroid

2022-03-29 01:39 UTC, JeongHyeongKim commented on packages/server/src/fcm/fcm.service.ts
> +  }
title, body가 not nullable한 속성이라면, 위에 검사하는 로직을 넣는게 좋을거같습니다.

```suggestion
  private message(to: string, data: Data, collapse_key: string) {
    const {title, body} = data;
    
    if(_.isNil(title) || _.isNil(body)){
        // some logics...
    }
    return {
      to,
      collapse_key,
      notification: {
        title: data.title,
        body: data.body,
        click_action: "Result3Activity",
      },
      data,
    };
  }
```

2022-03-29 01:39 UTC, JeongHyeongKim commented on packages/server/src/fcm/fcm.service.ts
> +import { Data } from "./fcm.interfaces";
path 설정이 잘 안되어있네요
나중에 제가 path 설정 일괄적으로 적용하겠습니다.

2022-03-29 10:29 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +  }
수정했습니다!

2022-03-29 10:29 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +  }
수정했습니다.

2022-03-29 10:29 UTC, ionc635 commented on packages/server/src/fcm/fcm.service.ts
> +import { Data } from "./fcm.interfaces";
확인했습니다!

2022-03-29 15:51 UTC, JeongHyeongKim approved these changes

2022-04-03 03:17 UTC, jaryapp approved these changes
😁😁

2022-04-03 07:03 UTC, merged