[admin] 로그인 페이지 UI 개발
CMI-OSS/cbnu-alrami pull request #47
Opened 2021-11-16 13:32 UTC by kingyong9169

## 👀 이슈

resolve #37 

## 📌 개요

로그인 페이지 개발입니다. form validation 구현의 효율성과 리렌더링 최소화를 위해 react-hook-form을 사용하였습니다.
네이버 로그인 UI를 참고했으며 react-icons 라이브러리를 사용하여 아이콘을 추가하였고 비밀번호 lock, unlock 기능을 넣었습니다.

## 👩‍💻 작업 사항

- [ ] 로그인 페이지 UI
- [ ] form validation
- [ ] 비밀번호 lock(input type: password), unlock(input type: text)

## ✅ 참고 사항
![login](https://user-images.githubusercontent.com/62797441/141994329-006bc6ac-b20a-4778-8639-b8cbb30fa711.gif)

<img width="299" alt="스크린샷 2021-11-16 오후 10 30 52" src="https://user-images.githubusercontent.com/62797441/141994454-7a02c354-2990-4042-a50b-cb78f74e947d.png">
로그인 버튼을 누르면 위 사진과 같이 form 데이터가 출력됩니다.

2021-11-17 10:56 UTC, soonitoon commented
로그인 UI 정말 깔끔하게 잘 만드셨네요!  제가 만든 시나리오 관리 보드 UI도 충북대 색으로 통일하는 것도 좋을 것 같습니다~ 아이디랑 비밀번호 정상적으로 출력되는 것도 확인했습니다.

2021-11-17 10:58 UTC, soonitoon commented
> 로그인 UI 정말 깔끔하게 잘 만드셨네요! 제가 만든 시나리오 관리 보드 UI도 충북대 색으로 통일하는 것도 좋을 것 같습니다~ 아이디랑 비밀번호 정상적으로 출력되는 것도 확인했습니다.

`shared` 디렉토리에 있는 컬러들도 나중에 회의를 통해 통합해서 정리해야겠습니다.

2021-11-17 11:40 UTC, jaryapp requested changes
UI가 정말 귀엽고 깔끔하네요 ㅎㅎ 브루니 고생많으셨어여!!

2021-11-17 11:40 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +    <main className={cx(style.loginForm)}>
요기서는 `cx` 안써두 될듯하네여
```suggestion
    <main className={style.loginForm}>
```

2021-11-17 11:40 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +          }
`style.idBox`가 공통이고 `classNameId` 값에 따라서 ` ${style.focus}`가 변하는거라면 `cx`를 활용하면 좋을것 같아요
```suggestion
          className={
            cx(style. idBox,{style.focus: classNameId})
          }
```
그리고 변수명도 `isFocusId` 이런식으로 변경하면 좋을것 같습니다

2021-11-17 11:40 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +            classNamePw ? `${style.pwBox} ${style.focus}` : `${style.pwBox}`
여기두 위와 동일합니다~

2021-11-17 11:40 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +            )}
여기두 클래스가 특정 값에 따라 바뀌는거면 `cx`를 활용 부탁드려요~

2021-11-17 11:42 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +    console.log(errors);
요즘에는 if-else 보다는 `얼리리턴`을 많이 사용하고 있어서 참고하시면 좋을것 같습니다~ [참고](http://mkseo.pe.kr/blog/?p=2631)

2021-11-17 11:44 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +  const [lock, setLock] = useState(true);
Boolean에 해당하는 변수명은 앞에 `is`접두어를 붙여주시는게 좋습니다 [참고](https://www.crocus.co.kr/1638)
e.g. `isLock`, `setIsLock`

2021-11-17 12:28 UTC, kingyong9169 reviewed
자세한 리뷰 감사합니다ㅎㅎ

2021-11-17 12:28 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +  const [lock, setLock] = useState(true);
반영하겠습니다~

2021-11-17 12:28 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +    console.log(errors);
반영하겠습니다~

2021-11-17 12:28 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +    <main className={cx(style.loginForm)}>
오호 반영하겠습니다~

2021-11-17 12:28 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +          }
오호 자세한 피드백 감사합니다~

2021-11-17 12:31 UTC, soonitoon commented on packages/admin/src/components/LoginForm/style.ts
> +      }
아이디/비밀번호 입력란이 포커스될 때마다 충북대 색으로 바뀌는 부분 좋은 것 같아요~
그런데 포커스 될 때 `border`넓이가 `input` 태그 안에 더해져서 포커스될 때마다 `input` 태그 안의 `placeholder`나 입력한 내용이 밀려나는 것 같습니다. 
혹시 `border` 대신 `outline`을 사용하는 건 어떨까요?

2021-11-17 12:31 UTC, soonitoon commented on packages/admin/src/components/LoginForm/index.tsx
> +          >
```javascript
() => {
  if (lock) setLock(false);
  else setLock(true);
}
```
요 부분을 `!` 연산자를 쓰면 더 간단하게 만들 수 있을 것 같습니다!

```javascript
() => setLock(!lock);
```

2021-11-17 12:31 UTC, soonitoon commented on packages/admin/src/components/LoginForm/index.tsx
> +          />
`input` 태그의 `type` 속성을 바꿔서 비밀번호 표시 여부를 달리 하는 게 신기하네요~ 나중에 인증 페이지 만들 때 써먹어야겠습니다. 🙏

2021-11-17 12:31 UTC, soonitoon commented on packages/admin/src/components/LoginForm/index.tsx
> +    <main className={cx(style.loginForm)}>
저는 emotion의 `cx()`가 여러 클래스 네임이나 스타일을 조합할 때 사용하는 걸로 알고 있어요. 여기서는 적용하려고 하는 스타일이 하나라서 `cx()`를 사용할 필요가 없을 것 같습니다!

2021-11-17 12:32 UTC, soonitoon commented on packages/admin/src/components/LoginForm/index.tsx
> +    <main className={cx(style.loginForm)}>
아이고... 리뷰가 pending 상태인줄도 모르고 있었네요 😂

2021-11-17 12:40 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +          >
앗 그러네욬ㅋㅋㅋ 감사합니당

2021-11-17 12:54 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/index.tsx
> +            )}
앗 여기는 lock에 따라 바뀌는 아이콘이 달라서 cx를 사용안해도 될 것 같습니당

2021-11-17 13:46 UTC, nohgijin approved these changes
브루니 수고하셨어요 ㅎㅎㅎ

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/App.tsx
>            <Route path="/" component={Home} />
```suggestion
          <Route path="/" exact component={Home} />
```
https://velopert.com/3417
exact를 붙여주는게 좋앙요~ 바꾸시는 김에 같이 바꿔주시면 감사하겠습니당

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/index.tsx
> +  useEffect(() => {
훅들은 최대한 위에서 써주세요!

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/index.tsx
> +              <AiOutlineLock className={style.icon} />
lock은 style.icon이고
unlock은 style.unLock이여서 안맞는 느낌?
통일감있게 style.lock으로 해도 좋을것같네요

2021-11-17 13:46 UTC, nohgijin commented on packages/shared/src/styles/index.ts
> +  $grayLine: "#c6c6c6",
grayLine보다는
gray.$100
gray.$200 
...
이런식으로 써요
채도가 높을수록 더 진한색으로!

또한 $cbnu가 메인 색이라면 $primary 이렇게 쓰는게 좋겠네요
보통 메인 색은 $primary로 써서

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/style.ts
> +  const id = cssHash();
id가 input인가요?
변수명만 보고 알아채긴 너무 어려워서 만약 input이라면
idInput 이렇게 표현하는 것도 좋을 것 같아요
근데 이거 한번에 선언할 방법이 없나..너무 기네요

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/style.ts
> +      }
password랑 구조가 너무 비슷해요
같은 스타일인데 같은 코드 두번 쓰는 느낌

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/index.tsx
> +interface FormProps {
FromProps대신 Props로 해주시면 좋을것같아용ㅎㅎ
사유)길게 쓰기 귀찮아서..ㅎㅎ

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/index.tsx
> +  const [message, setMessage] = useState("");
공백 들어가는거 확인해주세용

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/index.tsx
> +  const [message, setMessage] = useState("");
[ message, setMessage ]

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/style.ts
> +  const loginForm = css`
a css``
A styled.div``
나중에 논의

2021-11-17 13:46 UTC, nohgijin commented on packages/admin/src/components/LoginForm/style.ts
> +        box-shadow: 0 2px 6px 0 rgb(68 68 68 / 8%);
http://milooy.github.io/TIL/CSS/css-property-order.html#intro

2021-11-17 13:52 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +            )}
앗 그러네여~ ㅎㅎ

2021-11-17 13:54 UTC, jaryapp commented on packages/admin/src/components/LoginForm/style.ts
> +  const id = cssHash();
이거는 제가 개선할 방법을 찾을게요~

2021-11-17 13:55 UTC, jaryapp commented on packages/admin/src/components/LoginForm/index.tsx
> +  const [message, setMessage] = useState("");
@kingyong9169 이거는 저랑 vscode 설정 같이확인해요

2021-11-17 14:21 UTC, kingyong9169 commented on packages/admin/src/components/LoginForm/style.ts
> +      }
outline으로 하면 밖으로 튀어나와서 padding 조절해서 해결했슴다!

2021-11-17 14:24 UTC, soonitoon commented on packages/admin/src/components/LoginForm/style.ts
> +      }
넵넵~ 그 방법이 훨씬 깔끔한 것 같아요!

2021-11-17 15:38 UTC, kingyong9169 reviewed
다들 자세한 코드리뷰 정말 감사합니다ㅎㅎ 반영하면서 많이 배웠어요ㅎㅎ
앞으로 pr할 때 많이 고민해보고 하겠습니다~

2021-11-17 15:52 UTC, kingyong9169 commented on packages/shared/src/styles/index.ts
> +  $grayLine: "#c6c6c6",
$gray.$400으로 변경했습니다! [Gmarket color rule](https://gds.gmarket.co.kr/foundation/color)을 참고해서 400으로 정했습니다!

2021-11-17 16:22 UTC, jaryapp commented
retest this please

2021-11-17 16:28 UTC, jaryapp commented
@kingyong9169 넵 ㅎㅎ 근데 또 너무 고민하진 마시공 일단 PR 올리고 궁금하거나 애매한 부분은 PR에 내용 혹은 self-code review로 적어서 같이 고민해도 돼여~ 프로젝트 초반이니까 계속 이렇게 조금씩 맞춰가면 될것같아요  코드 리뷰 반영 하시느라 고생하셨습니당!

2021-11-19 02:00 UTC, vcho1958 approved these changes

2021-11-21 11:07 UTC, jaryapp approved these changes

2021-11-21 14:20 UTC, merged